spring:
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: datacenter1
logging:
  level:
    org.springframework.data.cassandra.core.cql.CqlTemplate: DEBUG